name: G+ Weekly Update
on:
  schedule:
    - cron: "0 0 * * */2"
  workflow_dispatch:

jobs:
    reporter:
        runs-on: ubuntu-latest
        name: G+ Weekly Update
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Install deps
            run: pip install -r requirements.txt
          - name: Grab newest G+ data from ASA
            run: |
              python ./asa_retrieve.py
              python ./zones_retrieve.py
          - name: Push updated files
            uses: test-room-7/action-update-file@v1.5.0
            with:
              file-path: data/*.csv
              commit-msg: "Updated G+ CSVs after latest bot run."
              github-token: ${{ secrets.GITHUB_TOKEN }}
